### PR TITLE
Set commit status from Jenkins also for special branches

### PR DESCRIPTION
**Pull request by msimberg**

### CODE REVIEW

**Comment by msimberg** [comment]
bors try

**Comment by msimberg** [comment]
bors try

**Comment by msimberg** [comment]
bors try

**Comment by msimberg** [comment]
It may still be too early to add all jenkins configurations to the required bors statuses (because of a few more flaky tests), but in principle that is at least possible with this change.

`bors try` is also now an alternative to trigger all builds, but builds triggered by that currently have useless build names on CDash (e.g. `trying-clang-13-debug`: https://cdash.cscs.ch/buildSummary.php?buildid=208335).

**Comment by msimberg** [comment]
bors try

**Review by hkaiser — DISMISSED** [review]
LGTM, thanks!

**Comment by msimberg** [comment]
Replaced by https://github.com/STEllAR-GROUP/hpx/pull/5736.

**Pull request closed without merging**
